a = float(input('enter number: '))
b = float(input('enter number: '))
if a==0 or b==0:
    print('Error: Please enter non-zero numbers.')
minus = abs(a - b)
plus = abs(a + b)
multiply = abs(a * b)
print('minus = ', minus)
print('plus = ', plus)
print('multiply = ', multiply)